apiVersion: v1
kind: Pod
metadata:
  name: tommy-pod-gpu
spec:
  containers:
  - name: demo
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
      requests:
        memory: 16Gi
        cpu: "2"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /persistentvol
      name: examplevol
  # volumes is a list of volume specifications
  volumes:
  - name: examplevol
    persistentVolumeClaim:
      claimName: tommy-vol
  # gpu stuff
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-3090-01.calit2.optiputer.net
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  tolerations:
  - effect: NoSchedule
    key: nautilus.io/gilpin-lab
    operator: Exists
