apiVersion: v1
kind: Pod
metadata:
  name: tommy-pod
spec:
  containers:
  - name: mypod
    image: centos:centos7
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    volumeMounts:
    - mountPath: /pvcvolume
      name: examplevol
  volumes:
    - name: examplevol
      PersistentVolumeClaim:
        claimName: tommy-vol
